# Generated by Django 3.2.3 on 2021-07-03 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('idMoneda', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de moneda')),
                ('nombreMoneda', models.CharField(max_length=50, verbose_name='Nombre de la moneda')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('NumIdentificaion', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='NumIdentificacion')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=20, verbose_name='Apellido')),
                ('direccion', models.CharField(max_length=20, verbose_name='direccion')),
                ('email', models.CharField(max_length=20, verbose_name='Numero')),
                ('pais', models.CharField(max_length=20, verbose_name='Pais')),
                ('contraseña', models.CharField(max_length=20, verbose_name='Constraseña')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroundZero.moneda')),
            ],
        ),
    ]
