# Generated by Django 3.2.3 on 2021-07-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundZero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.CharField(max_length=20, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Telefono'),
        ),
    ]
